import argparse
import csv
import json
import math
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path


FEATURE_KEYS = [
    "audio_rms",
    "audio_peak",
    "audio_zero_crossing_rate",
    "spectral_centroid_hz",
    "pitch_hz",
    "pitch_confidence",
]

SERVICE_EMOTION_MAP = {
    "neutral": "normal",
    "joy": "normal",
    "kind": "normal",
    "dry": "normal",
    "doubt": "normal",
    "shy": "normal",
    "hesitate": "normal",
    "sad": "frustrated",
    "serious": "frustrated",
    "anxious": "frustrated",
    "surprise": "frustrated",
    "hurry": "frustrated",
    "fear": "frustrated",
    "angry": "angry",
    "tease": "angry",
    "normal": "normal",
    "frustrated": "frustrated",
    "threatening": "threatening",
}


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as file:
        return list(csv.DictReader(file))


def to_float(value: str | None) -> float | None:
    if value is None or not str(value).strip():
        return None
    try:
        number = float(value)
    except ValueError:
        return None
    return number if math.isfinite(number) else None


def service_emotion(row: dict[str, str]) -> str:
    direct = row.get("service_emotion", "").strip().lower()
    if direct in {"normal", "frustrated", "angry", "threatening"}:
        return direct
    raw = row.get("emotion", "").strip().lower()
    return SERVICE_EMOTION_MAP.get(raw, "")


def mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else 0.0


def stddev(values: list[float], avg: float) -> float:
    if len(values) < 2:
        return 1.0
    variance = sum((value - avg) ** 2 for value in values) / (len(values) - 1)
    return max(math.sqrt(variance), 1e-9)


def feature_stats(rows: list[dict[str, str]]) -> dict[str, dict[str, float]]:
    stats = {}
    for key in FEATURE_KEYS:
        values = [value for row in rows if (value := to_float(row.get(key))) is not None]
        avg = mean(values)
        stats[key] = {
            "mean": round(avg, 8),
            "std": round(stddev(values, avg), 8),
            "min": round(min(values), 8) if values else 0,
            "max": round(max(values), 8) if values else 0,
        }
    return stats


def z(value: float, stat: dict[str, float]) -> float:
    return (value - stat["mean"]) / max(stat["std"], 1e-9)


def train_model(rows: list[dict[str, str]]) -> dict[str, object]:
    usable_rows = [
        row
        for row in rows
        if any(to_float(row.get(key)) is not None for key in FEATURE_KEYS)
    ]
    stats = feature_stats(usable_rows)
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in usable_rows:
        emotion = service_emotion(row)
        if emotion:
            grouped[emotion].append(row)

    model: dict[str, object] = {
        "version": 1,
        "trainedAt": datetime.now(timezone.utc).isoformat(),
        "featureKeys": FEATURE_KEYS,
        "stats": stats,
        "rows": len(usable_rows),
        "labelCounts": dict(sorted(Counter(service_emotion(row) or "unlabeled" for row in usable_rows).items())),
    }

    labeled_total = sum(len(items) for items in grouped.values())
    if labeled_total < 10 or len(grouped) < 2:
        model.update({
            "mode": "acoustic_baseline",
            "description": "Unlabeled SKT acoustic distribution model. Runtime uses calibrated acoustic arousal rules.",
        })
        return model

    centroids: dict[str, dict[str, float]] = {}
    for emotion, items in grouped.items():
        centroid = {}
        for key in FEATURE_KEYS:
            values = [value for row in items if (value := to_float(row.get(key))) is not None]
            if not values:
                continue
            centroid[key] = round(mean([z(value, stats[key]) for value in values]), 8)
        if centroid:
            centroids[emotion] = centroid

    model.update({
        "mode": "centroid",
        "description": "SKT emotion-index supervised centroid model for live acoustic emotion prediction.",
        "centroids": centroids,
    })
    return model


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train EmotionGuard live acoustic emotion model from SKT metadata CSV.")
    parser.add_argument("metadata_csv", help="CSV generated by extract_skt_emotion_metadata.py")
    parser.add_argument("--output", default="data/skt/skt_emotion_model.json")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    rows = read_rows(Path(args.metadata_csv))
    model = train_model(rows)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(model, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({
        "output": str(output),
        "mode": model.get("mode"),
        "rows": model.get("rows"),
        "labelCounts": model.get("labelCounts"),
    }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
